version: "3.3"
services:
  server:
    build :
      context: ./server
    ports:
      - "9000:9000"
    networks:
      - grpc-demo
  client:
    build :
      context: ./client
    ports:
      - "3000:3000"
    networks:
      - grpc-demo

networks:
  grpc-demo:
    driver: bridge